### ISSUE TITLE
Range of BigInt not supported?

### ISSUE THREAD

**Issue by russel** [def-/nim-bigints#1]
For reasons to do with investigating testing Nim code I am writing factorial with a number of different algorithms. For the external iterative version, I have the statement:
```nim
  for i in two .. n:
    result *= i
```
where two and n are BigInt values, but the compiler tells me:

> factorial.nim(13, 15) Info: template/generic instantiation from here
> lib/system.nim(1581, 4) Error: type mismatch: got (BigInt)
> but expected one of: 
> system.inc(x: var T, y: int)

the for statement is line 13. Does this mean ranges of BigInt are not supported out of the box?

**Comment by def-** [comment]
I tried implementing `inc`, but system's `..` doesn't use it. I guess it would also be necessary to implement `..` again, but then we would have an overlap between definitions for `..`. Not sure what's the best way to progress here.
