### ISSUE TITLE
LICENSE for bigints

### ISSUE THREAD

**Issue by alehander42** [def-/nim-bigints#15]
We wanted to use this library in a project, but it doesn't have a LICENSE.

**Comment by def-** [comment]
If you want performance and correctness I'd suggest wrapping gmp instead, which can be done nicely. There were a few examples floating around.

Otherwise I can of course add a license.

**Comment by dom96** [comment]
Is this not admissible in court? :P

https://github.com/def-/nim-bigints/blob/master/bigints.nimble#L6
