### ISSUE TITLE
bigints.nimble file format is wrong

### ISSUE THREAD

**Issue by sky-khan** [def-/nim-bigints#2]
bigints.nimble does not conform ini file format
it should use '=' not ':' as name-value seperator

**Comment by def-** [comment]
Same as every other nimble/babel file, right? Why is this a problem?

**Comment by sky-khan** [comment]
Because I'm writing a NimbleGUI and should write extra code to overcome this and I'm lazy :)

**Comment by def-** [comment]
I guess it will be easier to check how nimble parses it than changing all nimble files out there.

**Comment by sky-khan** [comment]
Well then, so be it
If I wasnt use Lazarus to write it there wont be a problem. Now I will not be able to use its default ini parser

**Comment by dom96** [comment]
You should be using Nimble's parser anyway.

**Comment by sky-khan** [comment]
How should I ? I already said I'm using Freepascal Lazarus for GUI. Should I compile an exe from nim side, launch a os process for the sake of parsing an ini and write another parser for its output ? thanks but no thanks.
Because my all attempts about using nim generated dynamic library from freepascal side has failed. I call NimInnerMain and it returns but any nim code which uses heap ends up crash at GC proc 'markstackandregisters'. I already tried with dev branch too

**Comment by dom96** [comment]
Why aren't you writing it in Nim?

**Comment by sky-khan** [comment]
Its only a part of my hobby project "NRolls", brand new IDE for Nim. I dont want to delve into another GUI library, plus  I dont like GTK on windows, plus I already know Delphi/Lazarus very well. And I need an IDE which has reaally working code explorer, code completion and navigation to learn a new language and its libraries. I dont know Nim enough yet.
