### ISSUE TITLE
Empty limbs when uninitialized

### ISSUE THREAD

**Issue by auxym** [def-/nim-bigints#26]
Consider the following:

```nim
var
    a: BigInt
    b: BigInt = 12.initBigInt

echo a*b
```
This results in the following stack trace:

```
[...]/scratch.nim(7) scratch
[...].nimble/pkgs/bigints-0.4.3/bigints.nim(484) *
[...].nimble/pkgs/bigints-0.4.3/bigints.nim(394) multiplication
[...].choosenim/toolchains/nim-#devel/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexError]
```

This is because `a.limbs` is `@[]`. Would it be possible for an uninitialized `BigInt` to default to `limbs = @[0]`, to be consistent with nim integers? Otherwise, maybe there could be a flag `initialized` that is checked before trying to operate on a `BigInt`, so we get slightly more readable errors. I'm not super proud about it, but tbh this took me a while to debug. To be fair, my actual code was slightly more complex and resulted in a zero BigInt not being initialized in a corner case.

**Comment by def-** [comment]
Sounds good but would require https://github.com/nim-lang/RFCs/issues/126

**Comment by auxym** [comment]
Yeah, I wasn't sure if/how it could be implemented in Nim. Good to know there's an RFC about it!
