### ISSUE TITLE
Negative BigInt

### ISSUE THREAD

**Issue by andreaferretti** [def-/nim-bigints#4]
It seems that bigints, as implemented here, are unsigned. I tried to do

```nim
let x = -initBigInt(1)
```
but it does not compile. Implementing unary negation as

```nim
proc `-`*(a: BigInt): BigInt = initBigInt(0) - a
```

leads to `SIGSEGV: Illegal storage access`.

Is there any reason why BigInts are implemented as positive numbers?

**Comment by def-** [comment]
Thanks, that was a bug in the assumptions of the term rewriting optimizations. This module is still not as well tested as it should be.

**Comment by andreaferretti** [comment]
Thank you! Would you mind publishing an updated version?

**Comment by def-** [comment]
Oh right, I knew I forgot something!
