### ISSUE TITLE
Off by one error in division

### ISSUE THREAD

**Issue by AB95** [def-/nim-bigints#5]
Nim:
![image](https://cloud.githubusercontent.com/assets/10396224/13204556/f385ec8c-d8ca-11e5-9671-1ce530ea3ff7.png)

Wolfram Alpha:
![image](https://cloud.githubusercontent.com/assets/10396224/13204559/fa3cba9c-d8ca-11e5-9505-7d108910253b.png)

Python:
![image](https://cloud.githubusercontent.com/assets/10396224/13204656/4ebccbc8-d8cd-11e5-9ed0-6a0aa26d9750.png)

Nim v0.13.0
Bigints downloaded earlier today, so also up to date

The calculation is 40!/(20!*20!)

**Comment by dom96** [comment]
Next time please don't put the code in an image.

```nim
import bigints

var x = initBigInt("815915283247897734345611269596115894272000000000")
var y = initBigInt("5919012181389927685417441689600000000")

echo(x div y)
```

Interesting bug though.

@def- Any ideas?

**Comment by def-** [comment]
This part of the division gets called and probably causes the off-by-one, but I'm not sure yet where the mistake is: https://github.com/def-/nim-bigints/blob/master/src/bigints.nim#L609-L616

**Comment by AB95** [comment]
Discovered a problem with this as well:

```nim
import bigints

var x = initBigInt("815915283247897734345611269596115894272000000000")
var y = initBigInt("20000000000")

echo x div y
```

It's returning 40795764162394886701185424564904152901 instead of 40795764162394886717280563479805794713. A difference of 16095138914901641812. 

As this code goes through the branch you mentioned there may be an issue with, I thought it could be the same problem.
